name: Release
on:
  create:  # Publish release on tag creation

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        if: github.event.ref_type == 'tag'
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v10
        if: github.event.ref_type == 'tag'
      - uses: olafurpg/setup-gpg@v3
        if: github.event.ref_type == 'tag'
      - name: Cache sbt
        if: github.event.ref_type == 'tag'
        uses: actions/cache@v3
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
            key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
      - run: sbt ci-release
        if: github.event.ref_type == 'tag'
        env:
          CI_SNAPSHOT_RELEASE: +publishSigned
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
